apiVersion: v1  # Specifies the API version for the service
kind: Service  # Defines the type of Kubernetes object (Service)
metadata:
  name: flask-app-service  # The name of the service
spec:
  selector:
    app: flask-app  # Selects pods with the label 'app: flask-app' to route traffic to
  ports:
  - protocol: TCP  # The protocol used for communication (TCP in this case)
    port: 80  # The port exposed by the service to the outside world
    targetPort: 5000  # The port on the container to which the service will forward traffic
  type: LoadBalancer  # The service type; LoadBalancer provisions an external IP to route traffic
